version: '3'

networks:
  nodriza:

services:

  # nginx
  nginx-nodriza-service:
    image: nginx:stable-alpine
    container_name: nginx-nodriza-container
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/project
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php-nodriza-service
      - mysql-nodriza-service
    tty: true
    networks:
      - nodriza

  # php
  php-nodriza-service:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    container_name: php-nodriza-container
    ports:
      - "9000:9000"
    volumes:
      - ./app:/var/www/project
    networks:
      - nodriza

  # mysql
  mysql-nodriza-service:
    image: mysql:8
    container_name: mysql-nodriza-container
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_USER: admin
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: admin
    networks:
      - nodriza
